/* Auto-generated by genmsg_cpp for file /home/alex/lego-nxt-car-like/nxt_rosjava_msgs/msg/JointCommand.msg */
#ifndef NXT_ROSJAVA_MSGS_MESSAGE_JOINTCOMMAND_H
#define NXT_ROSJAVA_MSGS_MESSAGE_JOINTCOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace nxt_rosjava_msgs
{
template <class ContainerAllocator>
struct JointCommand_ : public ros::Message
{
  typedef JointCommand_<ContainerAllocator> Type;

  JointCommand_()
  : name()
  , type()
  , effort(0.0)
  , speed(0.0)
  , angle(0.0)
  {
  }

  JointCommand_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , type(_alloc)
  , effort(0.0)
  , speed(0.0)
  , angle(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;

  typedef double _effort_type;
  double effort;

  typedef double _speed_type;
  double speed;

  typedef double _angle_type;
  double angle;


private:
  static const char* __s_getDataType_() { return "nxt_rosjava_msgs/JointCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "adb623484e6320b5fdb170c047a26f65"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string name\n\
string type\n\
float64 effort\n\
float64 speed\n\
float64 angle\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, name);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, effort);
    ros::serialization::serialize(stream, speed);
    ros::serialization::serialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, name);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, effort);
    ros::serialization::deserialize(stream, speed);
    ros::serialization::deserialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(name);
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(effort);
    size += ros::serialization::serializationLength(speed);
    size += ros::serialization::serializationLength(angle);
    return size;
  }

  typedef boost::shared_ptr< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct JointCommand
typedef  ::nxt_rosjava_msgs::JointCommand_<std::allocator<void> > JointCommand;

typedef boost::shared_ptr< ::nxt_rosjava_msgs::JointCommand> JointCommandPtr;
typedef boost::shared_ptr< ::nxt_rosjava_msgs::JointCommand const> JointCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nxt_rosjava_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adb623484e6320b5fdb170c047a26f65";
  }

  static const char* value(const  ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xadb623484e6320b5ULL;
  static const uint64_t static_value2 = 0xfdb170c047a26f65ULL;
};

template<class ContainerAllocator>
struct DataType< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nxt_rosjava_msgs/JointCommand";
  }

  static const char* value(const  ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
string type\n\
float64 effort\n\
float64 speed\n\
float64 angle\n\
\n\
";
  }

  static const char* value(const  ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.type);
    stream.next(m.effort);
    stream.next(m.speed);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nxt_rosjava_msgs::JointCommand_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "effort: ";
    Printer<double>::stream(s, indent + "  ", v.effort);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NXT_ROSJAVA_MSGS_MESSAGE_JOINTCOMMAND_H

